---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-pods-acc

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: monitor-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-amdin
subjects:
  - kind: ServiceAccount
    name: monitor-pods-acc
    namespace: default

kubectl create clusterrolebinding monitor-pods \
  --clusterrole=cluster-admin \
  --serviceaccount=default:monitor-pods-acc \
  --namespace=default