apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: koza/shell-operator-example:latest-py
    imagePullPolicy: Always
  serviceAccountName: monitor-pods-acc
